# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-added-large-files
          - id: pretty-format-json
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: check-symlinks
    - repo: https://github.com/commitizen-tools/commitizen
      rev: master
      hooks:
          - id: commitizen
            stages: [commit-msg]
